#!/bin/sh

PATH_TO_SCRIPT=$(cd ${0%/*} && echo $PWD/${0##*/})
EXAMPLEPREFIX=`dirname "$PATH_TO_SCRIPT"`

EXAMPLESUBDIR=@EXAMPLESUBDIR@
EXAMPLESUBDIRFROMPREFIX=@EXAMPLESUBDIRFROMPREFIX@
PREFIX=`echo $EXAMPLEPREFIX | sed s,$EXAMPLESUBDIRFROMPREFIX,,g`

PATH=$PREFIX/bin:$PATH LD_LIBRARY_PATH=$PREFIX/lib:$LD_LIBRARY_PATH DYLD_LIBRARY_PATH=$PREFIX/lib:$DYLD_LIBRARY_PATH $EXAMPLEPREFIX/@EXAMPLENAME@.wt --docroot $EXAMPLEPREFIX/@DOCROOTSUBFOLDER@ --approot $EXAMPLEPREFIX/@APPROOTSUBFOLDER@ --http-port 8080 --http-address 0.0.0.0 --resources-dir $PREFIX/share/Wt/resources $@
