#!/bin/bash

PATH_TO_SCRIPT=$(cd ${0%/*} && echo $PWD/${0##*/})
EXAMPLEPREFIX=`dirname "$PATH_TO_SCRIPT"`

EXAMPLESUBDIR=@EXAMPLESUBDIR@
EXAMPLESUBDIRFROMPREFIX=@EXAMPLESUBDIRFROMPREFIX@
PREFIX=`echo $EXAMPLEPREFIX | sed s,$EXAMPLESUBDIRFROMPREFIX,,g`

# Required until wthttp accepts a "--approot path" parameter
cd $EXAMPLEPREFIX

PATH=$PREFIX/bin:$PATH LD_LIBRARY_PATH=$PREFIX/lib:$LD_LIBRARY_PATH DYLD_LIBRARY_PATH=$PREFIX/lib:$DYLD_LIBRARY_PATH $EXAMPLEPREFIX/@EXAMPLENAME@.wt --docroot $EXAMPLEPREFIX/ --http-port 8080 --http-addr 0.0.0.0 $@
